name: terraform-compliance
description: BDD tests for Terraform

inputs:
  working-directory:
    description: The working directory for Terraform commands
    required: false
    default: ./terra

  tfplan_json_path:
    description: The path to the Terraform plan JSON file
    required: false
    default: "dist/update.tfplan.json"

  features_directory:
    description: BDD Gherkins folder
    required: false
    default: features

runs:
  using: composite
  steps:
    # SRC: https://github.com/terraform-compliance/github_action/releases/tag/0.3.0
    - uses: terraform-compliance/github_action@0357bd3be2b0a5739f5c09c64366d50f64a9056f
      name: terraform-compliance
      with:
        plan: ${{ inputs.working-directory }}/${{ inputs.tfplan_json_path }}
        features: ${{ inputs.working-directory }}/${{ inputs.features_directory }}
