#!/bin/bash

# TF_VAR_*
echo "TF_VAR_REPOSITORY_NAME = '${TF_VAR_REPOSITORY_NAME}'"
echo "TF_VAR_ENVIRONMENT = '${TF_VAR_ENVIRONMENT}'"
echo "TF_VAR_STACK_ID = '${TF_VAR_STACK_ID}'"

# ARM_ vars
echo "TF_VAR_ARM_LOCATION = '${TF_VAR_ARM_LOCATION}'"
echo "TF_VAR_ARM_RESOURCES_PREFIX = '${TF_VAR_ARM_RESOURCES_PREFIX}'"
