name: terraform fmt -check
description: Check Terraform formatting

inputs:
  working-directory:
    description: The working directory for Terraform commands
    required: false
    default: ./terra

  TF_CLI_ARGS_fmt:
    description: Additional options to pass to 'terraform fmt -check'
    required: false
    default: "-recursive -diff -list=true"

runs:
  using: composite
  steps:
    - name: echo TF_CLI_ARGS_fmt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "TF_CLI_ARGS_fmt"
        echo "env: '${{ env.TF_CLI_ARGS_fmt }}'"
        echo "inputs: '${{ inputs.TF_CLI_ARGS_fmt }}'"

    - name: terraform fmt -check
      shell: bash
      id: fmt-check
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -check ${{ inputs.TF_CLI_ARGS_fmt }}

    - name: terraform-pr-commenter
      uses: robburger/terraform-pr-commenter@v1
      # env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.fmt-check.outputs.stdout, steps.fmt-check.outputs.stderr) }}
        commenter_exitcode: ${{ steps.fmt-check.outputs.exitcode }}
