name: terraform plan
description: Terraform plan

inputs:
  working-directory:
    description: The working directory for Terraform commands
    required: false
    default: ./terra

  # NOTE: dist is relative to `chdir`
  TF_CLI_ARGS_plan:
    description: Additional options to pass to 'terraform plan'
    required: false
    default: "-out=dist/update.tfplan"

runs:
  using: composite
  steps:
    - name: echo TF_CLI_ARGS_plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "TF_CLI_ARGS_plan"
        echo "env: '${{ env.TF_CLI_ARGS_plan }}'"
        echo "inputs: '${{ inputs.TF_CLI_ARGS_plan }}'"

    - name: variables.ba.sh
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bash variables.ba.sh

    - name: terraform plan
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} plan ${{ inputs.TF_CLI_ARGS_plan }}
