name: terraform init
description: Initialize Terraform

inputs:
  working-directory:
    description: The working directory for Terraform commands
    required: false
    default: ./terra

  ls_cli_options:
    description: Additional options to pass to 'ls'
    required: false
    default: "-la"

  TF_CLI_ARGS_init:
    description: Additional options to pass to 'terraform init'
    required: false
    default: "-input=false"

  backend_override:
    description: Override TF_CLI_ARGS for 'terraform init'
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ls ${{ inputs.ls_cli_options }}

    # bash scripts/terraform/variables.ba.sh

    - name: echo TF_CLI_ARGS
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "TF_CLI_ARGS='${{ env.TF_CLI_ARGS }}'"

    - name: echo TF_CLI_ARGS_init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "TF_CLI_ARGS_init"
        echo "env: '${{ env.TF_CLI_ARGS_init }}'"
        echo "inputs: '${{ inputs.TF_CLI_ARGS_init }}'"

    - name: backend_override.tf
      if: ${{ inputs.backend_override == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo 'terraform { backend "local" {} }' > backend_override.tf

    - name: terraform init
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} init ${{ inputs.TF_CLI_ARGS_init }}
