name: "[C]ontinuous [D]elivery"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

  push:
    branches:
      - main

concurrency:
  # NOTE: Apparently terraform init or test does NOT create a lock.
  group: default
  cancel-in-progress: false

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "STACK_ID=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}

  validate:
    name: terraform
    needs: setup
    uses: ./.github/workflows/validate.yml
    with:
      backend_override: true
      tflint-version: latest

  ci_plan:
    name: "terraform @ ci-main"
    needs:
      - setup
      - validate
    uses: ./.github/workflows/plan.yml
    with:
      environment: ci-main
      validate: false
      features_directory: features
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  test:
    name: terraform
    needs: ci_plan
    uses: ./.github/workflows/test.yml
    with:
      backend_override: true
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}

  ci_apply_plan:
    name: "terraform @ ci-main"
    needs:
      - ci_plan
      - test
    uses: ./.github/workflows/apply_plan.yml
    with:
      environment: ci-main
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  ci_destroy:
    name: "terraform @ ci-main"
    needs: ci_apply_plan
    uses: ./.github/workflows/apply.yml
    if: always()
    with:
      environment: ci-main
      destroy: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  dev_apply:
    name: "terraform @ dev"
    needs: ci_apply_plan
    uses: ./.github/workflows/apply.yml
    with:
      environment: dev
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  dev_validate:
    name: "validate @ dev"
    needs: dev_apply
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: exit 0

  prod_apply:
    name: "terraform @ prod"
    needs: dev_validate
    uses: ./.github/workflows/apply.yml
    with:
      environment: prod
      TF_CLI_ARGS_apply: "-input=false -auto-approve"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  prod_validate:
    name: "validate @ prod"
    needs: prod_apply
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: exit 0
