name: integration_tests
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      environment:
        description: -var-file={ENV}.tfvars
        type: string
        required: false
        default: test

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      TF_CLI_ARGS_test:
        description: TF_CLI_ARGS_test
        type: string
        required: false
        default: "-test-directory=integration_tests -var-file=env/test.tfvars -junit-xml=test-results.xml"

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: -var-file={ENV}.tfvars
        type: string
        required: false
        default: test

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      TF_CLI_ARGS_test:
        description: TF_CLI_ARGS_test
        type: string
        required: false
        default: "-test-directory=integration_tests -var-file=env/test.tfvars -junit-xml=test-results.xml"

env:
  TF_IN_AUTOMATION: true

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test__integration_tests:
    name: test (integration_tests)
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_WORKSPACE: ${{ vars.ENVIRONMENT }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ref: ${{ inputs.ref || github.ref }}

      - uses: percebus/github-actions-terraform/.github/actions/setup@main
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}

      # TODO? break into `terraform -command=plan` & apply?
      - uses: percebus/github-actions-terraform/.github/actions/test@main
        with:
          working-directory: ${{ inputs.working-directory }}
          TF_CLI_ARGS_test: ${{ inputs.TF_CLI_ARGS_test }}

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          files_pattern: ${{ inputs.working-directory }}/**/*.xml
          # test-reporter inputs
          reporter: jest-junit
          tests_name: terraform test -test-directory=integration_tests
          list-suites: all
          list-tests: failed
          # test-summary inputs
          summary_title: "integration_tests Summary"
          # publish-test-deltas inputs
          publish-test-deltas: true
          comment_title: "`integration_tests` Deltas"
          check_name: integration_tests Deltas
