name: terraform plan

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      environment:
        description: environment
        type: string
        required: true

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      override:
        description: override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      validate:
        description: validate
        type: boolean
        required: false
        default: true

      destroy:
        description: destroy
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

      features_directory:
        description: terraform-compliance
        type: string
        required: false
        default: ""

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: environment
        type: string
        required: true

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      override:
        description: override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      validate:
        description: validate
        type: boolean
        required: false
        default: true

      destroy:
        description: destroy
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

      features_directory:
        description: terraform-compliance
        type: string
        required: false
        default: ""

env:
  terraform_action: ${{ inputs.destroy && 'destroy' || 'update' }}
  TF_IN_AUTOMATION: true
  TF_CLI_ARGS_plan: ${{ inputs.destroy && '-destroy' || '' }}

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_WORKSPACE: ${{ vars.ENVIRONMENT }}
    name: plan ${{ inputs.destroy && '-destroy' || '' }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ref: ${{ inputs.ref || github.ref }}

      - uses: percebus/github-actions-terraform/.github/actions/setup@main
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          override: ${{ inputs.override }}
          TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}

      - uses: percebus/github-actions-terraform/.github/actions/validate@main
        if: ${{ inputs.validate }}
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/plan@main
        with:
          github_token: ${{ github.token }}
          working-directory: ${{ inputs.working-directory }}
          header: ⚠️ `terraform plan ${{ env.TF_CLI_ARGS_plan }}`
          tfplan_path: dist/${{ env.terraform_action }}.tfplan
          include-json: ${{ inputs.features_directory == '' && 'false' || 'true' }}
          TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars ${{ inputs.TF_CLI_ARGS_plan }}"
          expand-comment: ${{ inputs.destroy && 'true' || 'false' }}

      - uses: percebus/github-actions-terraform/.github/actions/compliance@main
        if: ${{ inputs.features_directory != '' }}
        with:
          working-directory: ${{ inputs.working-directory }}
          tfplan_json_path: dist/${{ env.terraform_action }}.tfplan.json
          features_directory: ${{ inputs.features_directory }}

      - uses: percebus/github-actions-common/.github/actions/artifact-upload@main
        with:
          path: ${{ inputs.working-directory }}/dist
          name: tfplan_${{ env.terraform_action }}
          if-no-files-found: error
          overwrite: true
