name: "[Q]uality [A]ssurance"

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      environment:
        description: environment
        type: string
        required: true

      integration_tests_environment:
        description: environment
        type: string
        required: false
        default: test

      integration_tests_directory:
        description: integration tests directory
        type: string
        required: false
        default: ""

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false -reconfigure"

      tflint-version:
        description: tflint version
        type: string
        required: false
        default: ""

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

      features_directory:
        description: terraform-compliance
        type: string
        required: false
        default: ""

      TF_CLI_ARGS_apply:
        description: TF_CLI_ARGS_apply
        type: string
        required: false
        default: "-input=false"

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: environment
        type: string
        required: true

      integration_tests_environment:
        description: environment
        type: string
        required: false
        default: "test"

      integration_tests_directory:
        description: integration tests directory
        type: string
        required: false
        default: ""

      ref:
        description: The branch, tag or SHA to checkout.
        type: string
        required: false
        default: ""

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false -reconfigure"

      tflint-version:
        description: tflint version
        type: string
        required: false
        default: ""

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

      features_directory:
        description: terraform-compliance
        type: string
        required: false
        default: ""

      TF_CLI_ARGS_apply:
        description: TF_CLI_ARGS_apply
        type: string
        required: false
        default: "-input=false"

env:
  TF_IN_AUTOMATION: true

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: "env: local"
    uses: percebus/github-actions-terraform/.github/workflows/test.yml@main
    with:
      ref: ${{ inputs.ref }}
      working-directory: ${{ inputs.working-directory }}
      override: true
      TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}
      tflint-version: ${{ inputs.tflint-version }}

  integration_tests:
    name: "env: ${{ inputs.integration_tests_environment }}"
    needs: test
    if: ${{ inputs.integration_tests_directory != '' }}
    uses: percebus/github-actions-terraform/.github/workflows/integration_tests.yml@main
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      ref: ${{ inputs.ref }}
      working-directory: ${{ inputs.working-directory }}
      environment: ${{ inputs.integration_tests_environment }}
      TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_test: "-test-directory=${{ inputs.integration_tests_directory }} -var-file=env/${{ inputs.integration_tests_environment }}.tfvars -junit-xml=test-results.xml"

  terraform_plan_and_apply:
    name: "env: ${{ inputs.environment }}"
    needs: integration_tests
    uses: ./.github/workflows/plan_and_apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ inputs.environment }}
      features_directory: ${{ inputs.features_directory }}
      TF_CLI_ARGS_plan: "${{ inputs.TF_CLI_ARGS_plan }}"
      TF_CLI_ARGS_apply: "${{ inputs.TF_CLI_ARGS_apply }}"

  terraform_apply-destroy:
    name: "env: ${{ inputs.environment }}"
    needs: terraform_plan_and_apply
    uses: ./.github/workflows/apply.yml
    if: always()
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ inputs.environment }}
      destroy: true
