name: "Test workflows/*"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:

concurrency:
  # NOTE: Cancelling a plan and/or apply might corrupt the state.
  group: ${{ github.ref }}-default-ci
  cancel-in-progress: false

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "TF_CLI_ARGS_init=-reconfigure" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STACK_ID=main" >> $GITHUB_OUTPUT
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "STACK_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}
      environment: ${{ steps.set_variables.outputs.environment }}
      TF_CLI_ARGS_init: ${{ steps.set_variables.outputs.TF_CLI_ARGS_init }}

  #
  integration_tests:
    name: terraform
    needs: setup
    uses: ./.github/workflows/integration_tests.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    # with:
    #   environment: test
    #   TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
    #   TF_CLI_ARGS_test: ${{ needs.setup.outputs.TF_CLI_ARGS_test }}

  #
  terraform_plan_with_override:
    name: terraform (override.tf)
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}
      ref: ${{ github.event.workflow_run.head_branch }}
      override: true
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
      features_directory: features

  #
  terraform_apply:
    name: terraform
    needs:
      - setup
      - terraform_plan_with_override
    uses: ./.github/workflows/apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"

  #
  terraform_apply-destroy:
    name: terraform
    if: always()
    needs:
      - setup
      - terraform_apply
    uses: ./.github/workflows/apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      destroy: true

  #
  terraform_plan_and_apply:
    name: terraform
    needs:
      - setup
      - terraform_apply-destroy
    uses: ./.github/workflows/plan_and_apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      features_directory: features

  #
  terraform_plan-destroy_and_apply:
    name: terraform
    needs:
      - setup
      - terraform_plan_and_apply
    uses: ./.github/workflows/plan_and_apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      destroy: true

  # TODO? or XXX?
  # NOTE: Tested by examples__deployment
  # #
  # terraform_plan:
  #   name: terraform
  #   needs:
  #     - setup
  #     - terraform_apply-destroy
  #   uses: ./.github/workflows/plan.yml
  #   secrets:
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  #   with:
  #     environment: ${{ needs.setup.outputs.environment }}
  #     ref: ${{ github.event.workflow_run.head_branch }}
  #     TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
  #     TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"

  # #
  # terraform_apply_plan:
  #   name: terraform
  #   needs:
  #     - setup
  #     - terraform_plan
  #   uses: ./.github/workflows/apply_plan.yml
  #   secrets:
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  #   with:
  #     environment: ${{ needs.setup.outputs.environment }}
  #     ref: ${{ github.event.workflow_run.head_branch }}
  #     TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}

  # TODO? or XXX?
  # NOTE: Tested by examples__destroy
  # #
  # terraform_plan-destroy:
  #   name: terraform
  #   if: always()
  #   needs:
  #     - setup
  #     - terraform_apply_plan
  #   uses: ./.github/workflows/plan.yml
  #   secrets:
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  #   with:
  #     environment: ${{ needs.setup.outputs.environment }}
  #     ref: ${{ github.event.workflow_run.head_branch }}
  #     destroy: true

  # #
  # terraform_apply_plan-destroy:
  #   name: terraform
  #   needs:
  #     - setup
  #     - terraform_plan-destroy
  #   uses: ./.github/workflows/apply_plan.yml
  #   secrets:
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  #   with:
  #     environment: ${{ needs.setup.outputs.environment }}
  #     ref: ${{ github.event.workflow_run.head_branch }}
  #     destroy: true

  #
  # NOTE: plan_then_apply workflow is being tested by examples__deployment

  #
  # NOTE: plan-destroy_then_apply workflow is being tested by examples__destroy
