name: Test actions

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Cancelling an apply might corrupt the state.
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  pull-requests: write

env:
  TF_CLI_ARGS_init: -reconfigure
  TF_VAR_STACK_ID: ${{ github.event.pull_request.number }}
  TF_VAR_REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      environment: ${{ steps.set_variables.outputs.environment }}

  #
  terraform_test_with_override:
    name: terraform test w/ override.tf
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          override: true

      - uses: ./.github/actions/test

  #
  terraform_test_with_override__TF_CLI_ARGS_test__matrix:
    needs: terraform_test_with_override
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_test:
          - "-test-directory=./terra/tests -var ENVIRONMENT=bananas"
          - "-test-directory=./assets/terra/tests"
          - "-test-directory=./terra/tests -junit-xml=junit.xml"

    name: terraform test w/ override.tf ${{ matrix.TF_CLI_ARGS_test }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          override: true

      - uses: ./.github/actions/test
        with:
          TF_CLI_ARGS_test: ${{ matrix.TF_CLI_ARGS_test }}

  #
  terraform_plan:
    name: terraform plan
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'ci-main' || 'ci-branch' }}
    env:
      TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          override: true

      - uses: ./.github/actions/plan
        with:
          github_token: ${{ github.token }}

  #
  # TODO add plan_and_apply_with_dry_run

  #
  terraform_plan_and_apply_then_destroy:
    name: terraform apply -destroy
    runs-on: ubuntu-latest
    needs:
      - terraform_plan
      - setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      TF_CLI_ARGS_plan: "-var-file=./env/${{ needs.setup.outputs.environment }}.tfvars"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          override: true

      - uses: ./.github/actions/plan
        with:
          github_token: ${{ github.token }}

      - uses: ./.github/actions/apply
      - uses: ./.github/actions/plan
        with:
          github_token: ${{ github.token }}
          header: ""

      - uses: ./.github/actions/plan
        with:
          github_token: ${{ github.token }}
          TF_CLI_ARGS_plan: -destroy
          tfplan_path: dist/destroy.tfplan
          header: 🗑️ `terraform plan -destroy`

      - uses: ./.github/actions/apply
        with:
          TF_CLI_ARGS_apply: -destroy dist/destroy.tfplan

      - uses: ./.github/actions/plan
        with:
          github_token: ${{ github.token }}
          TF_CLI_ARGS_plan: -destroy
          tfplan_path: dist/destroy.tfplan
          header: ""
